from __future__ import annotations

import re
from pathlib import Path

from ggmlc.dialect.ggml.lowering import GGMLExecutionGraph, GGMLOpDef
from ggmlc.dialect.ggml.ops import GGMLOpCode
from ggmlc.ir.shape import AddDim, Dim, FloorDivDim, MulDim, StaticDim, SubDim, SymbolDim


def _sanitize_ident(name: str) -> str:
    """Sanitizes a tensor name into a valid C++ identifier."""
    ident = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if ident and ident[0].isdigit():
        ident = "t_" + ident
    return ident or "t_unnamed"


def _dim_to_cpp_expr(d: Dim | int | None) -> str:
    """Converts a Dimension expression into a C++ expression string."""
    if d is None:
        return "1"
    if isinstance(d, int):
        return str(d)
    if isinstance(d, StaticDim):
        return str(d.value)
    if isinstance(d, SymbolDim):
        return f'(symbols.count("{d.name}") ? symbols.at("{d.name}") : 1)'
    if isinstance(d, AddDim):
        return f"({_dim_to_cpp_expr(d.left)} + {_dim_to_cpp_expr(d.right)})"
    if isinstance(d, SubDim):
        return f"({_dim_to_cpp_expr(d.left)} - {_dim_to_cpp_expr(d.right)})"
    if isinstance(d, MulDim):
        return f"({_dim_to_cpp_expr(d.left)} * {_dim_to_cpp_expr(d.right)})"
    if isinstance(d, FloorDivDim):
        return f"({_dim_to_cpp_expr(d.left)} / {_dim_to_cpp_expr(d.right)})"
    return "1"


class GGMLCCppCodeGenerator:
    """Generates a standalone, human-readable C++ project from a GGMLExecutionGraph."""

    def __init__(self, graph: GGMLExecutionGraph, model_name: str = "model"):
        self.graph = graph
        self.model_name = _sanitize_ident(model_name)

    def generate_header(self) -> str:
        """Generates model.h containing weights struct and build_graph function."""
        lines: list[str] = [
            "// ============================================================================",
            f"// Generated C++ GGML Model Definition: {self.model_name}",
            "// Automatically generated by ggmlc. Supports CPU, CUDA, and Apple Metal.",
            "// ============================================================================",
            "#pragma once",
            "",
            "#include <string>",
            "#include <vector>",
            "#include <unordered_map>",
            "#include <memory>",
            "#include <cmath>",
            "#include <fstream>",
            "#include <iostream>",
            '#include "ggml.h"',
            '#include "ggml-alloc.h"',
            '#include "ggml-backend.h"',
            '#include "ggml-cpu.h"',
            "#if defined(GGML_USE_CUDA)",
            '#include "ggml-cuda.h"',
            "#endif",
            "#if defined(GGML_USE_METAL)",
            '#include "ggml-metal.h"',
            "#endif",
            '#include "gguf.h"',
            '#include "ggmlc/stdlib_kernels.h"',
            "",
            f"namespace {self.model_name} {{",
            "",
            "// ----------------------------------------------------------------------------",
            "// Model Parameter Weights Structure",
            "// ----------------------------------------------------------------------------",
            "struct Weights {",
        ]

        # Declare weight pointers
        for pid in self.graph.parameters:
            t = self.graph.tensors[pid]
            ident = _sanitize_ident(t.name)
            lines.append(
                f"    struct ggml_tensor* {ident} = nullptr; // Tensor ID {t.id} ({t.ggml_type.name})"
            )

        lines.extend(
            [
                "",
                "    // Initialize weight tensor descriptors in the GGML context",
                "    void init_tensors(struct ggml_context* ctx, struct gguf_context* gguf_ctx) {",
            ]
        )

        for pid in self.graph.parameters:
            t = self.graph.tensors[pid]
            ident = _sanitize_ident(t.name)
            shape_str = ", ".join(_dim_to_cpp_expr(d) for d in t.ne)
            lines.append(f'        // Parameter: "{t.name}"')
            lines.append(f'        int64_t tid_{t.id} = gguf_find_tensor(gguf_ctx, "{t.name}");')
            lines.append(f"        if (tid_{t.id} >= 0) {{")
            lines.append(
                f"            this->{ident} = ggml_new_tensor_4d(ctx, static_cast<enum ggml_type>({int(t.ggml_type)}), {shape_str});"
            )
            lines.append(f'            ggml_set_name(this->{ident}, "{t.name}");')
            lines.append("        }")

        lines.extend(
            [
                "    }",
                "",
                "    // Load tensor data bytes from GGUF file into backend memory buffer",
                "    bool load_data(struct gguf_context* gguf_ctx, const std::string& filepath) {",
                "        std::ifstream fin(filepath, std::ios::binary);",
                "        if (!fin.is_open()) return false;",
                "        size_t data_offset = gguf_get_data_offset(gguf_ctx);",
            ]
        )

        for pid in self.graph.parameters:
            t = self.graph.tensors[pid]
            ident = _sanitize_ident(t.name)
            lines.extend(
                [
                    f'        int64_t tid_{t.id} = gguf_find_tensor(gguf_ctx, "{t.name}");',
                    f"        if (tid_{t.id} >= 0 && this->{ident}) {{",
                    f"            size_t t_offset = data_offset + gguf_get_tensor_offset(gguf_ctx, tid_{t.id});",
                    f"            size_t t_size = gguf_get_tensor_size(gguf_ctx, tid_{t.id});",
                    "            std::vector<uint8_t> buf(t_size);",
                    "            fin.seekg(static_cast<std::streamoff>(t_offset), std::ios::beg);",
                    "            fin.read(reinterpret_cast<char*>(buf.data()), static_cast<std::streamsize>(t_size));",
                    f"            ggml_backend_tensor_set(this->{ident}, buf.data(), 0, t_size);",
                    "        }",
                ]
            )

        lines.extend(
            [
                "        return true;",
                "    }",
                "",
                "    // Convenience unified load method",
                '    void load(struct ggml_context* ctx, struct gguf_context* gguf_ctx, const std::string& filepath = "") {',
                "        init_tensors(ctx, gguf_ctx);",
                "        if (!filepath.empty()) {",
                "            load_data(gguf_ctx, filepath);",
                "        }",
                "    }",
                "};",
                "",
                "// ----------------------------------------------------------------------------",
                "// Computation Graph Builder",
                "// ----------------------------------------------------------------------------",
                "inline struct ggml_cgraph* build_graph(",
                "    struct ggml_context* ctx,",
                "    const Weights& weights,",
                "    const std::unordered_map<std::string, struct ggml_tensor*>& inputs,",
                "    const std::unordered_map<std::string, int64_t>& symbols = {}",
                ") {",
                "    struct ggml_cgraph* gf = ggml_new_graph(ctx);",
                "",
                "    // Mapping from tensor ID to allocated computation node",
                "    std::unordered_map<uint32_t, struct ggml_tensor*> tensors;",
                "",
                "    // Bind parameter tensors from weights",
            ]
        )

        for pid in self.graph.parameters:
            t = self.graph.tensors[pid]
            ident = _sanitize_ident(t.name)
            lines.append(f"    tensors[{t.id}] = weights.{ident};")

        lines.append("")
        lines.append("    // Bind model inputs")
        for in_id in self.graph.inputs:
            t = self.graph.tensors[in_id]
            lines.append(f'    auto in_it_{in_id} = inputs.find("{t.name}");')
            lines.append(f"    if (in_it_{in_id} != inputs.end()) {{")
            lines.append(f"        tensors[{in_id}] = in_it_{in_id}->second;")
            lines.append("    }")

        lines.append("")
        lines.append(
            "    // ------------------------------------------------------------------------"
        )
        lines.append("    // Execution Graph Forward Pass Nodes")
        lines.append(
            "    // ------------------------------------------------------------------------"
        )

        # Emit computational nodes
        for node in self.graph.nodes:
            node_code = self._generate_node_code(node)
            lines.extend(node_code)

        lines.append("")
        lines.append("    // Build graph outputs")
        for out_id in self.graph.outputs:
            lines.append(f"    if (tensors.find({out_id}) != tensors.end()) {{")
            lines.append(f"        ggml_build_forward_expand(gf, tensors[{out_id}]);")
            lines.append("    }")

        lines.extend(
            [
                "",
                "    return gf;",
                "}",
                "",
                f"}} // namespace {self.model_name}",
                "",
            ]
        )

        return "\n".join(lines)

    def _generate_node_code(self, node: GGMLOpDef) -> list[str]:
        lines = []
        op_name = node.name or f"node_{node.id}"
        lines.append(f"    // [{node.opcode.name}] {op_name} (Node {node.id})")

        out_id = node.outputs[0]
        inp_vars = [f"tensors[{i}]" for i in node.inputs]

        if node.opcode == GGMLOpCode.GGML_OP_ADD:
            lines.append(f"    tensors[{out_id}] = ggml_add(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_SUB:
            lines.append(f"    tensors[{out_id}] = ggml_sub(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_MUL:
            lines.append(f"    tensors[{out_id}] = ggml_mul(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_DIV:
            lines.append(f"    tensors[{out_id}] = ggml_div(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_MUL_MAT:
            if node.attributes.get("transpose_in0", 0) == 1:
                lines.append(
                    f"    struct ggml_tensor* t_tr_{node.id} = ggml_transpose(ctx, {inp_vars[0]});"
                )
                lines.append(
                    f"    tensors[{out_id}] = ggml_mul_mat(ctx, t_tr_{node.id}, {inp_vars[1]});"
                )
            else:
                lines.append(
                    f"    tensors[{out_id}] = ggml_mul_mat(ctx, {inp_vars[0]}, {inp_vars[1]});"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_UNARY:
            u_type = node.attributes.get("unary_op", "gelu")
            u_str = str(u_type).lower()
            if "gelu" in u_str or u_type == 8:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_GELU);"
                )
            elif "silu" in u_str or u_type == 10:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_SILU);"
                )
            elif "relu" in u_str or u_type == 6:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_RELU);"
                )
            elif "sigmoid" in u_str or u_type == 7:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_SIGMOID);"
                )
            elif "hardswish" in u_str or u_type == 11:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_HARDSWISH);"
                )
            elif "hardsigmoid" in u_str or u_type == 12:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_HARDSIGMOID);"
                )
            elif "tanh" in u_str or u_type == 4:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_TANH);"
                )
            elif "exp" in u_str or u_type == 13:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_EXP);"
                )
            elif "neg" in u_str or u_type == 2:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_NEG);"
                )
            elif "abs" in u_str or u_type == 0:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_ABS);"
                )
            else:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_RELU);"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_CLAMP:
            min_v = node.attributes.get("min", 0.0)
            max_v = node.attributes.get("max", 6.0)
            lines.append(
                f"    tensors[{out_id}] = ggml_clamp(ctx, {inp_vars[0]}, {min_v}f, {max_v}f);"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_CONV_2D:
            s0 = node.attributes.get("stride_w", 1)
            s1 = node.attributes.get("stride_h", 1)
            p0 = node.attributes.get("pad_w", 0)
            p1 = node.attributes.get("pad_h", 0)
            d0 = node.attributes.get("dilation_w", 1)
            d1 = node.attributes.get("dilation_h", 1)
            lines.append(
                f"    tensors[{out_id}] = ggml_conv_2d(ctx, {inp_vars[0]}, {inp_vars[1]}, {s0}, {s1}, {p0}, {p1}, {d0}, {d1});"
            )
            if len(inp_vars) > 2:
                lines.append(
                    f"    tensors[{out_id}] = ggml_add(ctx, tensors[{out_id}], {inp_vars[2]});"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_CONV_2D_DW:
            s0 = node.attributes.get("stride_w", 1)
            s1 = node.attributes.get("stride_h", 1)
            p0 = node.attributes.get("pad_w", 0)
            p1 = node.attributes.get("pad_h", 0)
            d0 = node.attributes.get("dilation_w", 1)
            d1 = node.attributes.get("dilation_h", 1)
            lines.append(
                f"    tensors[{out_id}] = ggml_conv_2d_dw(ctx, {inp_vars[0]}, {inp_vars[1]}, {s0}, {s1}, {p0}, {p1}, {d0}, {d1});"
            )
            if len(inp_vars) > 2:
                lines.append(
                    f"    tensors[{out_id}] = ggml_add(ctx, tensors[{out_id}], {inp_vars[2]});"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_POOL_2D:
            is_max = node.attributes.get("is_max", 0) != 0
            pool_enum = "GGML_OP_POOL_MAX" if is_max else "GGML_OP_POOL_AVG"
            is_adapt = node.attributes.get("is_adaptive", 0) != 0
            if is_adapt:
                lines.append(
                    f"    tensors[{out_id}] = ggml_pool_2d(ctx, {inp_vars[0]}, {pool_enum}, {inp_vars[0]}->ne[0], {inp_vars[0]}->ne[1], {inp_vars[0]}->ne[0], {inp_vars[0]}->ne[1], 0.0f, 0.0f);"
                )
            else:
                k0 = node.attributes.get("ksize_w", 2)
                k1 = node.attributes.get("ksize_h", 2)
                s0 = node.attributes.get("stride_w", k0)
                s1 = node.attributes.get("stride_h", k1)
                p0 = node.attributes.get("pad_w", 0)
                p1 = node.attributes.get("pad_h", 0)
                lines.append(
                    f"    tensors[{out_id}] = ggml_pool_2d(ctx, {inp_vars[0]}, {pool_enum}, {k0}, {k1}, {s0}, {s1}, {p0}.0f, {p1}.0f);"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_SOFT_MAX:
            lines.append(f"    tensors[{out_id}] = ggml_soft_max(ctx, {inp_vars[0]});")
        elif node.opcode == GGMLOpCode.GGML_OP_REPEAT:
            lines.append(f"    tensors[{out_id}] = ggml_repeat(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_RESHAPE:
            out_t = self.graph.tensors[out_id]
            ne_strs = [_dim_to_cpp_expr(d) for d in out_t.ne]
            lines.append(
                f"    tensors[{out_id}] = ggml_reshape_4d(ctx, {inp_vars[0]}, {', '.join(ne_strs)});"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_PERMUTE:
            ax = node.attributes.get("axes", [0, 1, 2, 3])
            while len(ax) < 4:
                ax.append(len(ax))
            lines.append(
                f"    tensors[{out_id}] = ggml_permute(ctx, {inp_vars[0]}, {ax[0]}, {ax[1]}, {ax[2]}, {ax[3]});"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_TRANSPOSE:
            lines.append(f"    tensors[{out_id}] = ggml_transpose(ctx, {inp_vars[0]});")
        elif node.opcode == GGMLOpCode.GGML_OP_NORM:
            w_arg = inp_vars[1] if len(inp_vars) > 1 else "nullptr"
            b_arg = inp_vars[2] if len(inp_vars) > 2 else "nullptr"
            eps = node.attributes.get("eps", 1e-5)
            lines.append(f"    tensors[{out_id}] = ggml_norm(ctx, {inp_vars[0]}, {eps}f);")
            if w_arg != "nullptr":
                lines.append(
                    f"    if ({w_arg}) {{ struct ggml_tensor* w = {w_arg}; if (ggml_can_repeat(w, tensors[{out_id}])) w = ggml_repeat(ctx, w, tensors[{out_id}]); tensors[{out_id}] = ggml_mul(ctx, tensors[{out_id}], w); }}"
                )
            if b_arg != "nullptr":
                lines.append(
                    f"    if ({b_arg}) {{ struct ggml_tensor* b = {b_arg}; if (ggml_can_repeat(b, tensors[{out_id}])) b = ggml_repeat(ctx, b, tensors[{out_id}]); tensors[{out_id}] = ggml_add(ctx, tensors[{out_id}], b); }}"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_RMS_NORM:
            w_arg = inp_vars[1] if len(inp_vars) > 1 else "nullptr"
            eps = node.attributes.get("eps", 1e-5)
            lines.append(f"    tensors[{out_id}] = ggml_rms_norm(ctx, {inp_vars[0]}, {eps}f);")
            if w_arg != "nullptr":
                lines.append(
                    f"    if ({w_arg}) {{ struct ggml_tensor* w = {w_arg}; if (ggml_can_repeat(w, tensors[{out_id}])) w = ggml_repeat(ctx, w, tensors[{out_id}]); tensors[{out_id}] = ggml_mul(ctx, tensors[{out_id}], w); }}"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_FLASH_ATTN_EXT:
            q_var = inp_vars[0]
            k_var = inp_vars[1]
            v_var = inp_vars[2] if len(inp_vars) > 2 else "nullptr"
            mask_var = inp_vars[3] if len(inp_vars) > 3 else "nullptr"
            scale = node.attributes.get("scale", 1.0)
            lines.append(
                f"    struct ggml_tensor* q_{node.id} = {q_var}; if (!ggml_is_contiguous(q_{node.id})) q_{node.id} = ggml_cont(ctx, q_{node.id});"
            )
            lines.append(
                f"    struct ggml_tensor* k_{node.id} = {k_var}; if (!ggml_is_contiguous(k_{node.id})) k_{node.id} = ggml_cont(ctx, k_{node.id});"
            )
            lines.append(
                f"    struct ggml_tensor* v_{node.id} = {v_var}; if (v_{node.id} && !ggml_is_contiguous(v_{node.id})) v_{node.id} = ggml_cont(ctx, v_{node.id});"
            )
            lines.append(
                f"    tensors[{out_id}] = ggml_flash_attn_ext(ctx, q_{node.id}, k_{node.id}, v_{node.id}, {mask_var}, {scale}f, 0.0f, 0.0f);"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_ROPE:
            n_dims = node.attributes.get("n_dims", 0)
            mode = node.attributes.get("mode", 0)
            freq_base = node.attributes.get("freq_base", 10000.0)
            freq_scale = node.attributes.get("freq_scale", 1.0)
            n_dims_expr = f"{inp_vars[0]}->ne[0]" if n_dims == 0 else str(n_dims)
            if "freq_base" in node.attributes:
                lines.append(
                    f"    tensors[{out_id}] = ggml_rope_ext(ctx, {inp_vars[0]}, {inp_vars[1]}, nullptr, {n_dims_expr}, {mode}, 0, {freq_base}f, {freq_scale}f, 0.0f, 1.0f, 0.0f, 0.0f);"
                )
            else:
                lines.append(
                    f"    tensors[{out_id}] = ggml_rope(ctx, {inp_vars[0]}, {inp_vars[1]}, {n_dims_expr}, {mode});"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_GET_ROWS:
            lines.append(f"    struct ggml_tensor* idx_{node.id} = {inp_vars[1]};")
            lines.append(
                f"    if (idx_{node.id}->type != GGML_TYPE_I32) idx_{node.id} = ggml_cast(ctx, idx_{node.id}, GGML_TYPE_I32);"
            )
            lines.append(
                f"    if (!ggml_is_contiguous(idx_{node.id})) idx_{node.id} = ggml_cont(ctx, idx_{node.id});"
            )
            lines.append(
                f"    tensors[{out_id}] = ggml_get_rows(ctx, {inp_vars[0]}, idx_{node.id});"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_CONCAT:
            dim = node.attributes.get("ggml_dim", node.attributes.get("dim", 0))
            lines.append(
                f"    tensors[{out_id}] = ggml_concat(ctx, {inp_vars[0]}, {inp_vars[1]}, {dim});"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_CONT:
            lines.append(f"    tensors[{out_id}] = ggml_cont(ctx, {inp_vars[0]});")
        elif node.opcode == GGMLOpCode.GGML_OP_SCALE:
            s_val = node.attributes.get("scale", 1.0)
            lines.append(f"    tensors[{out_id}] = ggml_scale(ctx, {inp_vars[0]}, {s_val}f);")
        elif node.opcode == GGMLOpCode.GGML_OP_CPY:
            out_t = self.graph.tensors[out_id]
            ne_strs = [_dim_to_cpp_expr(d) for d in out_t.ne]
            lines.append(
                f"    struct ggml_tensor* dst_{node.id} = ggml_new_tensor_4d(ctx, static_cast<enum ggml_type>({int(out_t.ggml_type)}), {', '.join(ne_strs)});"
            )
            lines.append(f"    tensors[{out_id}] = ggml_cpy(ctx, {inp_vars[0]}, dst_{node.id});")
        elif node.opcode == GGMLOpCode.GGML_OP_ARGMAX:
            lines.append(f"    tensors[{out_id}] = ggml_argmax(ctx, {inp_vars[0]});")
        elif node.opcode == GGMLOpCode.GGML_OP_DIAG_MASK_INF:
            n_past = node.attributes.get("n_past", 0)
            lines.append(
                f"    tensors[{out_id}] = ggml_diag_mask_inf(ctx, {inp_vars[0]}, {n_past});"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_VIEW:
            out_t = self.graph.tensors[out_id]
            ne_strs = [_dim_to_cpp_expr(d) for d in out_t.ne]
            offset = node.attributes.get("offset", 0)
            lines.append(
                f"    tensors[{out_id}] = ggml_view_4d(ctx, {inp_vars[0]}, {', '.join(ne_strs)}, {inp_vars[0]}->nb[1], {inp_vars[0]}->nb[2], {inp_vars[0]}->nb[3], {offset});"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_CUSTOM_BIAS_GELU:
            lines.append("    #if defined(GGML_USE_CUDA)")
            lines.append(
                f"    struct ggml_tensor* b_{node.id} = {inp_vars[1]}; if (ggml_can_repeat(b_{node.id}, {inp_vars[0]})) b_{node.id} = ggml_repeat(ctx, b_{node.id}, {inp_vars[0]});"
            )
            lines.append(
                f"    tensors[{out_id}] = ggml_gelu(ctx, ggml_add(ctx, {inp_vars[0]}, b_{node.id}));"
            )
            lines.append("    #else")
            lines.append(
                f"    tensors[{out_id}] = ggml_map_custom2(ctx, {inp_vars[0]}, {inp_vars[1]}, ggmlc_compute_forward_bias_gelu, GGML_N_TASKS_MAX, nullptr);"
            )
            lines.append("    #endif")
        elif node.opcode == GGMLOpCode.GGML_OP_CUSTOM_LAYER_NORM:
            w_arg = inp_vars[1] if len(inp_vars) > 1 else "nullptr"
            b_arg = inp_vars[2] if len(inp_vars) > 2 else "nullptr"
            eps = node.attributes.get("eps", 1e-5)
            lines.append("    #if defined(GGML_USE_CUDA)")
            lines.append(f"    tensors[{out_id}] = ggml_norm(ctx, {inp_vars[0]}, {eps}f);")
            if w_arg != "nullptr":
                lines.append(
                    f"    if ({w_arg}) {{ struct ggml_tensor* w = {w_arg}; if (ggml_can_repeat(w, tensors[{out_id}])) w = ggml_repeat(ctx, w, tensors[{out_id}]); tensors[{out_id}] = ggml_mul(ctx, tensors[{out_id}], w); }}"
                )
            if b_arg != "nullptr":
                lines.append(
                    f"    if ({b_arg}) {{ struct ggml_tensor* b = {b_arg}; if (ggml_can_repeat(b, tensors[{out_id}])) b = ggml_repeat(ctx, b, tensors[{out_id}]); tensors[{out_id}] = ggml_add(ctx, tensors[{out_id}], b); }}"
                )
            lines.append("    #else")
            lines.append(
                f"    tensors[{out_id}] = ggml_map_custom3(ctx, {inp_vars[0]}, {w_arg}, {b_arg}, ggmlc_compute_forward_layer_norm, GGML_N_TASKS_MAX, nullptr);"
            )
            lines.append("    #endif")
        elif node.opcode == GGMLOpCode.GGML_OP_CUSTOM_RMS_NORM:
            w_arg = inp_vars[1] if len(inp_vars) > 1 else "nullptr"
            eps = node.attributes.get("eps", 1e-5)
            lines.append("    #if defined(GGML_USE_CUDA)")
            lines.append(f"    tensors[{out_id}] = ggml_rms_norm(ctx, {inp_vars[0]}, {eps}f);")
            if w_arg != "nullptr":
                lines.append(
                    f"    if ({w_arg}) {{ struct ggml_tensor* w = {w_arg}; if (ggml_can_repeat(w, tensors[{out_id}])) w = ggml_repeat(ctx, w, tensors[{out_id}]); tensors[{out_id}] = ggml_mul(ctx, tensors[{out_id}], w); }}"
                )
            lines.append("    #else")
            lines.append(
                f"    tensors[{out_id}] = ggml_map_custom2(ctx, {inp_vars[0]}, {w_arg}, ggmlc_compute_forward_rms_norm, GGML_N_TASKS_MAX, nullptr);"
            )
            lines.append("    #endif")
        elif node.opcode == GGMLOpCode.GGML_OP_CUSTOM_SWIGLU:
            lines.append("    #if defined(GGML_USE_CUDA)")
            lines.append(
                f"    tensors[{out_id}] = ggml_mul(ctx, ggml_silu(ctx, {inp_vars[0]}), {inp_vars[1]});"
            )
            lines.append("    #else")
            lines.append(
                f"    tensors[{out_id}] = ggml_map_custom2(ctx, {inp_vars[0]}, {inp_vars[1]}, ggmlc_compute_forward_swiglu, GGML_N_TASKS_MAX, nullptr);"
            )
            lines.append("    #endif")
        else:
            lines.append(f"    // Generic fallback for opcode {node.opcode.name}")
            lines.append(f"    tensors[{out_id}] = {inp_vars[0]};")

        return lines

    def generate_main(self) -> str:
        """Generates ggmlc_main.cpp standalone execution entry point."""
        return f"""// ============================================================================
// Standalone GGML Backend Model Runner: {self.model_name}
// Automatically generated by ggmlc. Supports CPU, CUDA, and Apple Metal.
// ============================================================================

#include "{self.model_name}.h"
#include <iostream>
#include <vector>
#include <chrono>
#include <cstring>
#include <string>

int main(int argc, char** argv) {{
    std::string gguf_path = "model.gguf";
    std::string device = "auto";
    int n_threads = 4;

    for (int i = 1; i < argc; ++i) {{
        if (std::strcmp(argv[i], "--model") == 0 && i + 1 < argc) {{
            gguf_path = argv[++i];
        }} else if (std::strcmp(argv[i], "--threads") == 0 && i + 1 < argc) {{
            n_threads = std::atoi(argv[++i]);
        }} else if (std::strcmp(argv[i], "--device") == 0 && i + 1 < argc) {{
            device = argv[++i];
        }}
    }}

    std::cout << "=== Running {self.model_name} with GGML Backend ===" << std::endl;
    std::cout << "GGUF Model: " << gguf_path << " | Device: " << device << " | Threads: " << n_threads << std::endl;

    // 1. Initialize execution backend (CPU, CUDA, or Apple Metal)
    ggml_backend_t backend = nullptr;
#if defined(GGML_USE_CUDA)
    if (device == "auto" || device.rfind("cuda", 0) == 0) {{
        int dev_idx = 0;
        if (device.size() > 5 && device[4] == ':') {{
            dev_idx = std::stoi(device.substr(5));
        }}
        backend = ggml_backend_cuda_init(dev_idx);
        if (backend) {{
            std::cout << "Initialized GGML CUDA Backend on GPU " << dev_idx << std::endl;
        }}
    }}
#endif
#if defined(GGML_USE_METAL)
    if (!backend && (device == "auto" || device == "metal")) {{
        backend = ggml_backend_metal_init();
        if (backend) {{
            std::cout << "Initialized GGML Metal Backend" << std::endl;
        }}
    }}
#endif
    if (!backend) {{
        backend = ggml_backend_cpu_init();
        if (ggml_backend_is_cpu(backend)) {{
            ggml_backend_cpu_set_n_threads(backend, n_threads);
        }}
        std::cout << "Initialized GGML CPU Backend (" << n_threads << " threads)" << std::endl;
    }}

    // 2. Initialize GGML context for graph structures (no_alloc = true)
    struct ggml_init_params params = {{
        /*.mem_size   =*/ 128 * 1024 * 1024,
        /*.mem_buffer =*/ nullptr,
        /*.no_alloc   =*/ true,
    }};
    struct ggml_context* ctx = ggml_init(params);
    if (!ctx) {{
        std::cerr << "Failed to allocate GGML context" << std::endl;
        if (backend) ggml_backend_free(backend);
        return 1;
    }}

    // 3. Instantiate weights and register descriptors from GGUF metadata
    {self.model_name}::Weights weights;

    struct gguf_init_params gguf_params = {{ true, nullptr }};
    struct gguf_context* gguf_ctx = gguf_init_from_file(gguf_path.c_str(), gguf_params);
    if (!gguf_ctx) {{
        std::cerr << "Warning: Could not open GGUF file: " << gguf_path << " (proceeding with uninitialized weights)" << std::endl;
    }} else {{
        weights.init_tensors(ctx, gguf_ctx);
    }}

    // 4. Prepare input nodes
    std::unordered_map<std::string, struct ggml_tensor*> inputs;
    struct ggml_tensor* in_tensor = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, 16);
    ggml_set_name(in_tensor, "input");
    inputs["input"] = in_tensor;

    // 5. Build computation graph
    struct ggml_cgraph* gf = {self.model_name}::build_graph(ctx, weights, inputs);

    // 6. Allocate memory on the target backend
    ggml_backend_buffer_t buffer = ggml_backend_alloc_ctx_tensors(ctx, backend);
    if (!buffer) {{
        std::cerr << "Failed to allocate backend tensor memory" << std::endl;
        ggml_free(ctx);
        ggml_backend_free(backend);
        if (gguf_ctx) gguf_free(gguf_ctx);
        return 1;
    }}

    // 7. Load parameter tensor data from GGUF into backend buffer
    if (gguf_ctx) {{
        weights.load_data(gguf_ctx, gguf_path);
    }}

    // 8. Initialize input data via backend transfer
    std::vector<float> dummy_data(16, 1.0f);
    ggml_backend_tensor_set(in_tensor, dummy_data.data(), 0, 16 * sizeof(float));

    // 9. Execute computation on target backend
    auto t0 = std::chrono::high_resolution_clock::now();
    enum ggml_status status = ggml_backend_graph_compute(backend, gf);
    auto t1 = std::chrono::high_resolution_clock::now();
    double elapsed_ms = std::chrono::duration<double, std::milli>(t1 - t0).count();

    if (status == GGML_STATUS_SUCCESS) {{
        std::cout << "Execution completed successfully in " << elapsed_ms << " ms" << std::endl;
    }} else {{
        std::cerr << "Backend execution failed with status: " << status << std::endl;
    }}

    // Clean up
    if (gguf_ctx) gguf_free(gguf_ctx);
    ggml_backend_buffer_free(buffer);
    ggml_free(ctx);
    ggml_backend_free(backend);
    return (status == GGML_STATUS_SUCCESS) ? 0 : 1;
}}
"""

    def generate_cmakelists(self) -> str:
        """Generates CMakeLists.txt for compiling the generated C++ project."""
        return f"""cmake_minimum_required(VERSION 3.14)
project({self.model_name}_standalone LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

option(ENABLE_CUDA "Enable GGML CUDA GPU backend" OFF)
option(ENABLE_METAL "Enable GGML Metal GPU backend" OFF)

find_package(Threads REQUIRED)

if (ENABLE_CUDA)
    enable_language(CUDA)
    add_compile_definitions(GGML_USE_CUDA)
    set(GGML_BACKEND_LIBS ggml ggml-base ggml-cpu ggml-cuda Threads::Threads)
elseif (ENABLE_METAL)
    find_library(FOUNDATION_FRAMEWORK Foundation REQUIRED)
    find_library(METAL_FRAMEWORK Metal REQUIRED)
    find_library(METALKIT_FRAMEWORK MetalKit REQUIRED)
    add_compile_definitions(GGML_USE_METAL)
    set(GGML_BACKEND_LIBS ggml ggml-base ggml-cpu ggml-metal ${{FOUNDATION_FRAMEWORK}} ${{METAL_FRAMEWORK}} ${{METALKIT_FRAMEWORK}} Threads::Threads)
else()
    set(GGML_BACKEND_LIBS ggml_lib Threads::Threads)
endif()

add_executable({self.model_name}_run
    ggmlc_main.cpp
)

target_include_directories({self.model_name}_run PRIVATE
    ${{CMAKE_CURRENT_SOURCE_DIR}}
)

target_link_libraries({self.model_name}_run PRIVATE
    ${{GGML_BACKEND_LIBS}}
)
"""


def generate_cpp_project(
    graph: GGMLExecutionGraph,
    output_dir: str | Path,
    model_name: str = "model",
) -> dict[str, Path]:
    """Generates a complete standalone C++ project in output_dir."""
    out_p = Path(output_dir)
    out_p.mkdir(parents=True, exist_ok=True)

    codegen = GGMLCCppCodeGenerator(graph, model_name=model_name)

    # 1. model.h
    header_path = out_p / f"{codegen.model_name}.h"
    header_path.write_text(codegen.generate_header(), encoding="utf-8")

    # 2. ggmlc_main.cpp
    main_path = out_p / "ggmlc_main.cpp"
    main_path.write_text(codegen.generate_main(), encoding="utf-8")

    # 3. CMakeLists.txt
    cmake_path = out_p / "CMakeLists.txt"
    cmake_path.write_text(codegen.generate_cmakelists(), encoding="utf-8")

    return {
        "header": header_path,
        "main": main_path,
        "cmake": cmake_path,
    }
