from __future__ import annotations

import re
from pathlib import Path

from ggmlc.dialect.ggml.lowering import GGMLExecutionGraph, GGMLOpDef
from ggmlc.dialect.ggml.ops import GGMLOpCode
from ggmlc.ir.shape import StaticDim


def _sanitize_ident(name: str) -> str:
    """Sanitizes a tensor name into a valid C++ identifier."""
    ident = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if ident and ident[0].isdigit():
        ident = "t_" + ident
    return ident or "t_unnamed"


class GGMLCCppCodeGenerator:
    """Generates a standalone, human-readable C++ project from a GGMLExecutionGraph."""

    def __init__(self, graph: GGMLExecutionGraph, model_name: str = "model"):
        self.graph = graph
        self.model_name = _sanitize_ident(model_name)

    def generate_header(self) -> str:
        """Generates model.h containing weights struct and build_graph function."""
        lines: list[str] = [
            "// ============================================================================",
            f"// Generated C++ GGML Model Definition: {self.model_name}",
            "// Automatically generated by ggmlc. Do not edit unless customizing kernels.",
            "// ============================================================================",
            "#pragma once",
            "",
            "#include <string>",
            "#include <vector>",
            "#include <unordered_map>",
            "#include <memory>",
            "#include <cmath>",
            '#include "ggml.h"',
            '#include "gguf.h"',
            '#include "ggmlc/stdlib_kernels.h"',
            "",
            f"namespace {self.model_name} {{",
            "",
            "// ----------------------------------------------------------------------------",
            "// Model Parameter Weights Structure",
            "// ----------------------------------------------------------------------------",
            "struct Weights {",
        ]

        # Declare weight pointers
        for pid in self.graph.parameters:
            t = self.graph.tensors[pid]
            ident = _sanitize_ident(t.name)
            lines.append(
                f"    struct ggml_tensor* {ident} = nullptr; // Tensor ID {t.id} ({t.ggml_type.name})"
            )

        lines.extend(
            [
                "",
                "    // Load model weights from a GGUF context",
                "    void load(struct ggml_context* ctx, struct gguf_context* gguf_ctx) {",
            ]
        )

        for pid in self.graph.parameters:
            t = self.graph.tensors[pid]
            ident = _sanitize_ident(t.name)
            shape_str = ", ".join(str(d.value if isinstance(d, StaticDim) else 1) for d in t.ne)
            lines.append(f'        // Parameter: "{t.name}"')
            lines.append(f'        int64_t tid_{t.id} = gguf_find_tensor(gguf_ctx, "{t.name}");')
            lines.append(f"        if (tid_{t.id} >= 0) {{")
            lines.append(
                f"            this->{ident} = ggml_new_tensor_4d(ctx, static_cast<enum ggml_type>({int(t.ggml_type)}), {shape_str});"
            )
            lines.append(f'            ggml_set_name(this->{ident}, "{t.name}");')
            lines.append("            // Raw data pointer is mapped from GGUF container")
            lines.append("        }")

        lines.extend(
            [
                "    }",
                "};",
                "",
                "// ----------------------------------------------------------------------------",
                "// Computation Graph Builder",
                "// ----------------------------------------------------------------------------",
                "inline struct ggml_cgraph* build_graph(",
                "    struct ggml_context* ctx,",
                "    const Weights& weights,",
                "    const std::unordered_map<std::string, struct ggml_tensor*>& inputs,",
                "    const std::unordered_map<std::string, int64_t>& symbols = {}",
                ") {",
                "    struct ggml_cgraph* gf = ggml_new_graph(ctx);",
                "",
                "    // Mapping from tensor ID to allocated computation node",
                "    std::unordered_map<uint32_t, struct ggml_tensor*> tensors;",
                "",
                "    // Bind parameter tensors from weights",
            ]
        )

        for pid in self.graph.parameters:
            t = self.graph.tensors[pid]
            ident = _sanitize_ident(t.name)
            lines.append(f"    tensors[{t.id}] = weights.{ident};")

        lines.append("")
        lines.append("    // Bind model inputs")
        for in_id in self.graph.inputs:
            t = self.graph.tensors[in_id]
            lines.append(f'    auto in_it_{in_id} = inputs.find("{t.name}");')
            lines.append(f"    if (in_it_{in_id} != inputs.end()) {{")
            lines.append(f"        tensors[{in_id}] = in_it_{in_id}->second;")
            lines.append("    }")

        lines.append("")
        lines.append(
            "    // ------------------------------------------------------------------------"
        )
        lines.append("    // Execution Graph Forward Pass Nodes")
        lines.append(
            "    // ------------------------------------------------------------------------"
        )

        # Emit computational nodes
        for node in self.graph.nodes:
            node_code = self._generate_node_code(node)
            lines.extend(node_code)

        lines.append("")
        lines.append("    // Build graph outputs")
        for out_id in self.graph.outputs:
            lines.append(f"    if (tensors.find({out_id}) != tensors.end()) {{")
            lines.append(f"        ggml_build_forward_expand(gf, tensors[{out_id}]);")
            lines.append("    }")

        lines.extend(
            [
                "",
                "    return gf;",
                "}",
                "",
                f"}} // namespace {self.model_name}",
                "",
            ]
        )

        return "\n".join(lines)

    def _generate_node_code(self, node: GGMLOpDef) -> list[str]:
        lines = []
        op_name = node.name or f"node_{node.id}"
        lines.append(f"    // [{node.opcode.name}] {op_name} (Node {node.id})")

        out_id = node.outputs[0]
        inp_vars = [f"tensors[{i}]" for i in node.inputs]

        if node.opcode == GGMLOpCode.GGML_OP_ADD:
            lines.append(f"    tensors[{out_id}] = ggml_add(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_SUB:
            lines.append(f"    tensors[{out_id}] = ggml_sub(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_MUL:
            lines.append(f"    tensors[{out_id}] = ggml_mul(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_DIV:
            lines.append(f"    tensors[{out_id}] = ggml_div(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_MUL_MAT:
            if node.attributes.get("transpose_in0", 0) == 1:
                lines.append(
                    f"    struct ggml_tensor* t_tr_{node.id} = ggml_transpose(ctx, {inp_vars[0]});"
                )
                lines.append(
                    f"    tensors[{out_id}] = ggml_mul_mat(ctx, t_tr_{node.id}, {inp_vars[1]});"
                )
            else:
                lines.append(
                    f"    tensors[{out_id}] = ggml_mul_mat(ctx, {inp_vars[0]}, {inp_vars[1]});"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_UNARY:
            u_type = node.attributes.get("unary_op", "gelu")
            if "gelu" in str(u_type).lower():
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_GELU);"
                )
            elif "silu" in str(u_type).lower():
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_SILU);"
                )
            elif "relu" in str(u_type).lower():
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_RELU);"
                )
            elif "tanh" in str(u_type).lower():
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_TANH);"
                )
            else:
                lines.append(
                    f"    tensors[{out_id}] = ggml_unary(ctx, {inp_vars[0]}, GGML_UNARY_OP_GELU);"
                )
        elif node.opcode == GGMLOpCode.GGML_OP_SOFT_MAX:
            lines.append(f"    tensors[{out_id}] = ggml_soft_max(ctx, {inp_vars[0]});")
        elif node.opcode == GGMLOpCode.GGML_OP_REPEAT:
            lines.append(f"    tensors[{out_id}] = ggml_repeat(ctx, {inp_vars[0]}, {inp_vars[1]});")
        elif node.opcode == GGMLOpCode.GGML_OP_RESHAPE:
            # Reshape dimensions
            out_t = self.graph.tensors[out_id]
            ne_strs = [str(d.value if isinstance(d, StaticDim) else 1) for d in out_t.ne]
            lines.append(
                f"    tensors[{out_id}] = ggml_reshape_4d(ctx, {inp_vars[0]}, {', '.join(ne_strs)});"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_PERMUTE:
            ax = node.attributes.get("axes", [0, 1, 2, 3])
            while len(ax) < 4:
                ax.append(len(ax))
            lines.append(
                f"    tensors[{out_id}] = ggml_permute(ctx, {inp_vars[0]}, {ax[0]}, {ax[1]}, {ax[2]}, {ax[3]});"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_TRANSPOSE:
            lines.append(f"    tensors[{out_id}] = ggml_transpose(ctx, {inp_vars[0]});")
        elif node.opcode == GGMLOpCode.GGML_OP_CUSTOM_BIAS_GELU:
            lines.append(
                f"    tensors[{out_id}] = ggml_map_custom2(ctx, {inp_vars[0]}, {inp_vars[1]}, ggmlc_compute_forward_bias_gelu, GGML_N_TASKS_MAX, nullptr);"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_CUSTOM_LAYER_NORM:
            w_arg = inp_vars[1] if len(inp_vars) > 1 else "nullptr"
            b_arg = inp_vars[2] if len(inp_vars) > 2 else "nullptr"
            lines.append(
                f"    tensors[{out_id}] = ggml_map_custom3(ctx, {inp_vars[0]}, {w_arg}, {b_arg}, ggmlc_compute_forward_layer_norm, GGML_N_TASKS_MAX, nullptr);"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_CUSTOM_RMS_NORM:
            w_arg = inp_vars[1] if len(inp_vars) > 1 else "nullptr"
            lines.append(
                f"    tensors[{out_id}] = ggml_map_custom2(ctx, {inp_vars[0]}, {w_arg}, ggmlc_compute_forward_rms_norm, GGML_N_TASKS_MAX, nullptr);"
            )
        elif node.opcode == GGMLOpCode.GGML_OP_CUSTOM_SWIGLU:
            lines.append(
                f"    tensors[{out_id}] = ggml_map_custom2(ctx, {inp_vars[0]}, {inp_vars[1]}, ggmlc_compute_forward_swiglu, GGML_N_TASKS_MAX, nullptr);"
            )
        else:
            lines.append(f"    // Generic fallback for opcode {node.opcode.name}")
            lines.append(f"    tensors[{out_id}] = {inp_vars[0]};")

        return lines

    def generate_main(self) -> str:
        """Generates ggmlc_main.cpp standalone execution entry point."""
        return f"""// ============================================================================
// Standalone GGML Model Runner: {self.model_name}
// Automatically generated by ggmlc.
// ============================================================================

#include "{self.model_name}.h"
#include <iostream>
#include <vector>
#include <chrono>
#include <cstring>

int main(int argc, char** argv) {{
    std::string gguf_path = "model.gguf";
    int n_threads = 4;

    for (int i = 1; i < argc; ++i) {{
        if (std::strcmp(argv[i], "--model") == 0 && i + 1 < argc) {{
            gguf_path = argv[++i];
        }} else if (std::strcmp(argv[i], "--threads") == 0 && i + 1 < argc) {{
            n_threads = std::atoi(argv[++i]);
        }}
    }}

    std::cout << "=== Running {self.model_name} with GGML ===" << std::endl;
    std::cout << "GGUF Model: " << gguf_path << " | Threads: " << n_threads << std::endl;

    // 1. Initialize GGML & GGUF context
    struct ggml_init_params params = {{
        /*.mem_size   =*/ 128 * 1024 * 1024,
        /*.mem_buffer =*/ nullptr,
        /*.no_alloc   =*/ false,
    }};
    struct ggml_context* ctx = ggml_init(params);
    if (!ctx) {{
        std::cerr << "Failed to allocate GGML context" << std::endl;
        return 1;
    }}

    // 2. Instantiate and load weights
    {self.model_name}::Weights weights;

    struct gguf_init_params gguf_params = {{ true, nullptr }};
    struct gguf_context* gguf_ctx = gguf_init_from_file(gguf_path.c_str(), gguf_params);
    if (gguf_ctx) {{
        weights.load(ctx, gguf_ctx);
        gguf_free(gguf_ctx);
    }}

    // 3. Prepare inputs
    std::unordered_map<std::string, struct ggml_tensor*> inputs;
    struct ggml_tensor* in_tensor = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, 16);
    std::vector<float> dummy_data(16, 1.0f);
    std::memcpy(in_tensor->data, dummy_data.data(), 16 * sizeof(float));
    inputs["input"] = in_tensor;

    // 4. Build graph
    auto t0 = std::chrono::high_resolution_clock::now();
    struct ggml_cgraph* gf = {self.model_name}::build_graph(ctx, weights, inputs);

    // 5. Execute computation
    ggml_graph_compute_with_ctx(ctx, gf, n_threads);
    auto t1 = std::chrono::high_resolution_clock::now();
    double elapsed_ms = std::chrono::duration<double, std::milli>(t1 - t0).count();

    std::cout << "Execution completed in " << elapsed_ms << " ms" << std::endl;

    ggml_free(ctx);
    return 0;
}}
"""

    def generate_cmakelists(self) -> str:
        """Generates CMakeLists.txt for compiling the generated C++ project."""
        return f"""cmake_minimum_required(VERSION 3.14)
project({self.model_name}_standalone LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Find ggmlc runtime / ggml library
find_package(Threads REQUIRED)

add_executable({self.model_name}_run
    ggmlc_main.cpp
)

target_include_directories({self.model_name}_run PRIVATE
    ${{CMAKE_CURRENT_SOURCE_DIR}}
)

target_link_libraries({self.model_name}_run PRIVATE
    Threads::Threads
)
"""


def generate_cpp_project(
    graph: GGMLExecutionGraph,
    output_dir: str | Path,
    model_name: str = "model",
) -> dict[str, Path]:
    """Generates a complete standalone C++ project in output_dir."""
    out_p = Path(output_dir)
    out_p.mkdir(parents=True, exist_ok=True)

    codegen = GGMLCCppCodeGenerator(graph, model_name=model_name)

    # 1. model.h
    header_path = out_p / f"{codegen.model_name}.h"
    header_path.write_text(codegen.generate_header(), encoding="utf-8")

    # 2. ggmlc_main.cpp
    main_path = out_p / "ggmlc_main.cpp"
    main_path.write_text(codegen.generate_main(), encoding="utf-8")

    # 3. CMakeLists.txt
    cmake_path = out_p / "CMakeLists.txt"
    cmake_path.write_text(codegen.generate_cmakelists(), encoding="utf-8")

    return {
        "header": header_path,
        "main": main_path,
        "cmake": cmake_path,
    }
